import type { Metadata } from 'next';
import Link from 'next/link';
import { getSiteSettings } from '@/lib/content';
export const metadata:Metadata={title:'About',description:'Meet Prudent Dubai Properties, the property-focused website from the Prudent Dubai group.'};
export default async function AboutPage(){const site=await getSiteSettings();return <>
  <section className="section"><div className="container"><span className="eyebrow">About Prudent Dubai Properties</span><h1 className="display">Property decisions deserve the same clarity as business decisions.</h1><p className="lede">Prudent Dubai Properties is the property-focused website from the Prudent Dubai group. It was created to help clients explore Dubai opportunities through structured information, documented sources and a practical conversation about their requirements.</p></div></section>
  <section className="section section-soft"><div className="container"><div className="editorial-grid"><div className="feature-panel"><span className="eyebrow">Our role</span><h2 className="section-title">We are a property dealer, not a listing portal.</h2><p>Prudent Dubai Properties helps clients across Dubai&apos;s residential areas and property types. We do not publish live listings or public prices on this website. Instead, we start with your requirements and share suitable options, pricing and availability in a direct conversation.</p></div><div className="side-stack"><article className="mini-panel"><div className="icon-box">01</div><h3>Requirement-led</h3><p>Area, property type and purpose come before any recommendation.</p></article><article className="mini-panel"><div className="icon-box">02</div><h3>Continuity</h3><p>Clients can also access the wider group&apos;s UAE business setup, accounting and compliance services when relevant.</p></article></div></div></div></section>
  <section className="section"><div className="container"><span className="eyebrow">Established presence</span><h2 className="section-title">Connected to the wider Prudent Dubai team.</h2><div className="info-grid"><article className="info-card"><h3>Dubai</h3><p>{site.dubaiOffice}</p></article><article className="info-card"><h3>Sharjah</h3><p>{site.sharjahOffice}</p></article><article className="info-card"><h3>Mumbai</h3><p>{site.mumbaiOffice}</p></article></div><div className="button-row"><a className="button button-secondary" href={site.sisterWebsite} target="_blank" rel="noopener noreferrer">Visit PrudentDubai.com ↗</a><Link className="button button-primary" href="/contact">Talk to the team</Link></div></div></section>
  </>}
