import type { Metadata } from 'next';
import Link from 'next/link';
import { getSiteSettings } from '@/lib/content';
export const metadata:Metadata={title:'About',description:'Meet Prudent Dubai Properties, the property-focused website from the Prudent Dubai group.'};
export default async function AboutPage(){const site=await getSiteSettings();return <>
  <section className="section page-intro"><div className="container"><span className="eyebrow">About us</span><h1 className="display">Property guidance that starts with you.</h1><p className="lede">Prudent Dubai Properties helps buyers explore areas, property types, costs, and purchase details across Dubai.</p></div></section>
  <section className="section section-soft"><div className="container"><div className="editorial-grid editorial-grid-balanced"><div className="feature-panel"><h2 className="section-title">A more focused way to search.</h2><p>We begin with where you want to buy, how much you plan to spend, and when you want to move. This keeps the conversation relevant from the start.</p></div><div className="side-stack"><article className="mini-panel"><div className="icon-box">01</div><h3>Property scope</h3><p>Apartments, villas, townhouses, ready homes, and off-plan projects.</p></article><article className="mini-panel"><div className="icon-box">02</div><h3>What we review</h3><p>Current prices, payment terms, availability, and documents.</p></article><article className="mini-panel"><div className="icon-box">03</div><h3>Wider support</h3><p>The Prudent Dubai group also provides UAE business, accounting, and compliance services.</p></article></div></div></div></section>
  <section className="section"><div className="container"><h2 className="section-title">Our offices</h2><p className="lede">Meet the wider Prudent Dubai team in Dubai, Sharjah, or Mumbai.</p><div className="info-grid"><article className="info-card"><h3>Dubai</h3><p>{site.dubaiOffice}</p></article><article className="info-card"><h3>Sharjah</h3><p>{site.sharjahOffice}</p></article><article className="info-card"><h3>Mumbai</h3><p>{site.mumbaiOffice}</p></article></div><div className="button-row"><a className="button button-secondary" href={site.sisterWebsite} target="_blank" rel="noopener noreferrer">Visit PrudentDubai.com ↗</a><Link className="button button-primary" href="/contact">Talk to the team</Link></div></div></section>
  </>}
